BaseUrl = "http://www.caffeinatedbrad.com/"
languageCode = "en-uk"
title = "Caffeinated Brad"

[author]
  name = "Bradley Jones"
  github = "bradleyjones"
  twitter = "caffeinatedbrad"
  email = "caffeinatedbrad@gmail.com"
  gaID = "UA-41298595-2"
